### ISSUE TITLE
Creating more than one compute node

### ISSUE THREAD

**Issue by beekhof** [redhat-openstack/tripleo-quickstart#67]
If I add two extra compute nodes to ha.yaml, ie:

```
overcloud_nodes:
  - name: control_0
    flavor: control
  - name: control_1
    flavor: control
  - name: control_2
    flavor: control
  - name: compute_0
    flavor: compute
  - name: compute_1
    flavor: compute
  - name: compute_2
    flavor: compute

```

`instackenv` contains all 6 nodes however I still only end up with one compute node after running `./overcloud-deploy.sh`

Any pointers where I should start looking?
